ATMManagement.MvcApp/Controllers/AtmController.cs
using ATMManagement.MvcApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Net.NetworkInformation;
using System.Reflection.Metadata;

namespace ATMManagement.MvcApp
{
    public class AtmController : Controller
    {
		private readonly AppDbContext _context;

		public AtmController(AppDbContext context)
		{
			_context = context;
		}

		[ActionName("Index")]
        public IActionResult AtmIndex()
        {
            return View("AtmIndex");
        }

        [HttpPost]
        [ActionName("Login")]
        public async Task<IActionResult> AtmLogin(UserModel reqModel)
        {
            var card = await _context.User.FirstOrDefaultAsync(x => x.CardNumber == reqModel.CardNumber && x.Pin == reqModel.Pin);

            if (card is null)
            {
                TempData["Message"] = "Card not recognized. Please try again!";
                TempData["IsSuccess"] = false;
            }
            return Json(card);
        }

        [ActionName("Create")]
        public IActionResult AtmCreate()
        {
            return View("AtmCreate");
        }

        [HttpPost]
        [ActionName("Save")]
        public async Task<IActionResult> AtmSave(UserModel reqModel)
        {
            await _context.User.AddAsync(reqModel);
            int result = await _context.SaveChangesAsync();

            string message = result > 0 ? "Register Successful." : "Register Failed.";
          
            MessageModel model = new MessageModel(result > 0, message);
            return Json(model);
        }

        [ActionName("Transaction")]
        public async Task<IActionResult> AtmTransaction(int id)
        {
            var card = await _context.User.AsNoTracking().FirstOrDefaultAsync(x => x.Id == id);
            if (card is null)
            {
                TempData["Message"] = "User ID not found.";
                TempData["IsSuccess"] = false;
            }
            return View("AtmTransaction",card);
        }

        [ActionName("Balance")]
        public async Task<IActionResult> AtmBalance(int id)
        {
            var card = await _context.User.AsNoTracking().FirstOrDefaultAsync(x => x.Id == id);
           
            return View("AtmBalance", card);
        }

        [ActionName("Deposit")]
        public async Task<IActionResult> AtmDeposit(int id)
        {
            var card = await _context.User.AsNoTracking().FirstOrDefaultAsync(x => x.Id == id);

            return View("AtmDeposit",card);
        }

        [HttpPost]
        [ActionName("Deposit")]
        public async Task<IActionResult> AtmDeposit(int id, UserModel reqModel)
        {
            var card = await _context.User.FirstOrDefaultAsync(x => x.Id == id);
            if (card is null)
            {
                TempData["Message"] = "User ID not found.";
                TempData["IsSuccess"] = false;
                return Json(card);
            }

            if(reqModel.Balance <= 0)
            {
                MessageModel model1 = new MessageModel(false, "Please fill deposit amount");
                return Json(model1);
            }
            card.Balance += reqModel.Balance;
            _context.User.Entry(card).State = EntityState.Modified;
            int result = _context.SaveChanges();
            string message = result > 0 ? "Deposit Successful." : "Deposit Failed.";

            MessageModel model = new MessageModel(result > 0, message);
            return Json(model);
        }

        [ActionName("Withdraw")]
        public async Task<IActionResult> AtmWithdraw(int id)
        {
            var card = await _context.User.AsNoTracking().FirstOrDefaultAsync(x => x.Id == id);

            return View("AtmWithdraw",card);
        }

        [HttpPost]
        [ActionName("Withdraw")]
        public async Task<IActionResult> AtmWithdraw(int id, UserModel reqModel)
        {
            var card = await _context.User.FirstOrDefaultAsync(x => x.Id == id);
            if (card is null)
            {
                TempData["Message"] = "User ID not found.";
                TempData["IsSuccess"] = false;
                return Json(card);
            }
            if (reqModel.Balance > card.Balance)
            {
                MessageModel model1 = new MessageModel(false, "Insufficient balance amount");
                return Json(model1);
            }

            card.Balance -= reqModel.Balance;
            _context.User.Entry(card).State = EntityState.Modified;
            int result = _context.SaveChanges();
            string message = result > 0 ? "Withdraw Successful." : "Withdraw Failed.";

            MessageModel model = new MessageModel(result > 0, message);
            return Json(model);
        }

        [ActionName("ChangePin")]
        public async Task<IActionResult> AtmChangePin(int id)
        {
            var card = await _context.User.AsNoTracking().FirstOrDefaultAsync(x => x.Id == id);

            return View("AtmChangePin", card);
        }

        [HttpPost]
        [ActionName("ChangePin")]
        public async Task<IActionResult> AtmChangePin(int id , UserModel reqModel , int newpin, int confirmpin)
        {
            var card = await _context.User.AsNoTracking().FirstOrDefaultAsync(x => x.Id == id);

            if (card is null)
            {
                TempData["Message"] = "Card isn't recognized.";
                TempData["IsSuccess"] = false;
            }
            else
            {
                if (card.Pin == reqModel.Pin)
                {
                    if (newpin == confirmpin)
                    {
                        card.Pin = newpin;
                        _context.User.Entry(card).State = EntityState.Modified;
                        int result = _context.SaveChanges();
                        string message = result > 0 ? "Successful." : "Failed.";

                        MessageModel model1 = new MessageModel(result > 0, message);
                        return Json(model1);
                    }
                    else
                    {
                        MessageModel model1 = new MessageModel(false,"Not match PIN numbers");
                        return Json(model1);
                    }
                }
                MessageModel model = new MessageModel(false, "Current PIN number is invalid");
                return Json(model);
            }
            return Json(card);

        }
    }
}

ATMManagement.MvcApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]ATMManagement.MvcApp</title>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ladda-bootstrap/0.9.4/ladda.min.css" integrity="sha512-zB1n/jwQD1XiJf3rDBfZVm5xqngjw1C48MYyJ8XOd/7OLvDbjUmY9+gGyeJORcYXSv3qFOZ3VdHAoullPFHIYA==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ATMManagement.MvcApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ATM</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Atm" asp-action="Index">Login</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <h4 class="display-4 text-secondary text-center">Welcome to ATM</h4><br />
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/ladda-bootstrap/0.9.4/spin.min.js" integrity="sha512-qByKQKO3eTwzJtP8Y395YbP45QyYZNpJfYu8jfFpWgFTK2xWIiOER7G+63EoXk475fBFzY6HIhbEUio6m72EaQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/ladda-bootstrap/0.9.4/ladda.min.js" integrity="sha512-OxowQ96EheBKRxTivGsizVvTK8bWt2xZlymiMZ9MArbmOmuxbv+2IlC46k4gZPhZH5eVQAm0F6lk9Yt6M4xu7A==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="~/js/custom.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>